import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { useState } from 'react';
import { Analytics } from "@vercel/analytics/react"


const poppins = Poppins({
   subsets: ["latin"], weight: '500' });

export const metadata: Metadata = {
  title: "Imagen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
