# Generated by Django 5.0.3 on 2024-04-02 04:52

import generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.png', upload_to=generator.models.image_upload_path),
        ),
    ]
